In [5]:
import numpy as np

In [43]:
# arr=np.random.randint(low = 1, high = 20)
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
arr2=arr.reshape(4,5)
print(arr2)
arr2[:,4]=0
print(arr2)
# arr2[0][4]=arr2[1][4]=arr2[2][4]=arr2[3][4]=0
arr3=arr2.flatten(order='C')
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  0]
 [ 6  7  8  9  0]
 [11 12 13 14  0]
 [16 17 18 19  0]]
[ 1  2  3  4  0  6  7  8  9  0 11 12 13 14  0 16 17 18 19  0]


In [7]:
task2 = np.random.randint(10,50, size=(5,5))
print(task2)
print('\nROW WISE')
for t in range(5):
    print(f'row: {t}')
    print(f'mean: {np.mean(task2[:,t])}\n sum: {np.sum(task2[:,t])}\n Min: {np.min(task2[:,t])}\n MAX: {np.max(task2[:,t])}\n')
print('\nCOLUMN WISE')
for t in range(5):
    print(f'Column: {t}')
    print(f'mean: {np.mean(task2[t,:])}\n sum: {np.sum(task2[t,:])}\n Min: {np.min(task2[t,:])}\n MAX: {np.max(task2[t,:])}\n')

[[41 22 23 11 27]
 [41 17 32 19 48]
 [35 23 34 25 27]
 [17 29 26 32 39]
 [19 23 12 35 38]]

ROW WISE
row: 0
mean: 30.6
 sum: 153
 Min: 17
 MAX: 41

row: 1
mean: 22.8
 sum: 114
 Min: 17
 MAX: 29

row: 2
mean: 25.4
 sum: 127
 Min: 12
 MAX: 34

row: 3
mean: 24.4
 sum: 122
 Min: 11
 MAX: 35

row: 4
mean: 35.8
 sum: 179
 Min: 27
 MAX: 48


COLUMN WISE
Column: 0
mean: 24.8
 sum: 124
 Min: 11
 MAX: 41

Column: 1
mean: 31.4
 sum: 157
 Min: 17
 MAX: 48

Column: 2
mean: 28.8
 sum: 144
 Min: 23
 MAX: 35

Column: 3
mean: 28.6
 sum: 143
 Min: 17
 MAX: 39

Column: 4
mean: 25.4
 sum: 127
 Min: 12
 MAX: 38



In [22]:
task3=np.identity(4,int)
np.fill_diagonal(task3,5)
task3[3,:]=1

print(task3)

[[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [1 1 1 1]]


In [31]:
task4= np.random.randint(0,20, size=15)
unii=np.unique(task4)
print(f'Count of Unique: {len(unii)}\nUNIQUE ELEMENTS: {unii}')
indicess=[]
for k in range(len(task4)):
    if task4[k]>10:
        indicess.append(k)
        
print('original array',task4)
print('Indices for element > 10: ', indicess)

Count of Unique: 10
UNIQUE ELEMENTS: [ 4  5  6 10 14 15 16 17 18 19]
original array [ 6  4  4 10 15  6 19 18 17  5 17 14  4 14 16]
Indices for element > 10:  [4, 6, 7, 8, 10, 11, 13, 14]


In [42]:
task5= np.random.rand(3,4)
print(task5)
task5_2=np.around(task5,2)
print(task5_2)
task5_3=task5_2
task5_3[:,1]=0.5
print(task5_3)


[[0.81995126 0.38815007 0.5234694  0.14504429]
 [0.60330105 0.06517461 0.40729842 0.72905108]
 [0.98688436 0.42984641 0.42899849 0.72194989]]
[[0.82 0.39 0.52 0.15]
 [0.6  0.07 0.41 0.73]
 [0.99 0.43 0.43 0.72]]
[[0.82 0.5  0.52 0.15]
 [0.6  0.5  0.41 0.73]
 [0.99 0.5  0.43 0.72]]
