**TASK1**

In [4]:
import numpy as np
import random

In [11]:
player_stats = np.array([[180, 75, 20], [175, 80, 25], [190, 85, 30]])
print(player_stats)

[[180  75  20]
 [175  80  25]
 [190  85  30]]


In [12]:
max_points_index = np.argmax(player_stats[:,2])
# print(player_stats[:,2])
player_stats[max_points_index, 1] += random.randint(1,10)
print(player_stats)

[[180  75  20]
 [175  80  25]
 [190  94  30]]


In [14]:
new_player = np.append(player_stats,[[185, 78, 15]],axis=0)
print(new_player)

[[180  75  20]
 [175  80  25]
 [190  94  30]
 [185  78  15]]


In [27]:

new_player = np.insert(player_stats,1,[140, 65, 11],axis=0)
print(new_player)


[[180  75  20]
 [140  65  11]
 [170  65  10]
 [175  80  25]
 [190  94  30]]


In [28]:
min_points_index = np.argmin(new_player[:,2])
# print(min_points_index)
new_player = np.delete(new_player,min_points_index,axis=0)
print(new_player)

[[180  75  20]
 [140  65  11]
 [175  80  25]
 [190  94  30]]


**TASK2**

In [34]:

purchase_amounts = np.array([100, 150, 200, 250])
item_counts = np.array([2, 3, 4, 5])
item_shallow=item_counts[:]
purchase_deep=purchase_amounts.copy()
conc=np.concatenate((item_shallow,purchase_deep),axis=0)
print(conc)
condition = conc >= 150
split_array = [conc[condition], conc[~condition]]
# splits=np.split(conc,4)
print(split_array)
purchase_amounts[2]=-200
item_counts[1]=-3
print(purchase_deep,'deep-copy',purchase_amounts,'og')
print(item_counts,'shallow-copy',item_shallow,'og')


[  2   3   4   5 100 150 200 250]
[array([150, 200, 250]), array([  2,   3,   4,   5, 100])]
[100 150 200 250] deep-copy [ 100  150 -200  250] og
[ 2 -3  4  5] shallow-copy [ 2 -3  4  5] og
